customhost = "aamux0sao89b00.ck2reqkczao9.us-east-1.rds.amazonaws.com"
customuser = "DBuser"
custompass = "Bait3273"
customdb = "ebdb"
custombucket = "my-cloud-computing-assignment-bucket"
customregion = "us-east-1"
